name: SoupCore
version: '${project.version}'
main: org.genesismc.SoupCore.SoupCore
api-version: 1.20
commands:
  kits:
    description: Open the kit selector
  refill:
    description: Refill your inventory with soup for 200 credits
  repair:
    description: Repair your armour and tools for 50 credits
  bounty:
    description: Bounty System
    aliases: ['bounties']
  stats:
    description: Stats Command
    usage: /stats [player]
  spawn:
    description: Teleport to spawn
  coinflip:
    description: Flip a coin!
    aliases: ['cf']
  pay:
    description: Pay another player credits
    usage: "§c/pay <player> <amount>"
  balance:
    description: Check your credit balance
    usage: "§c/bal [player]"
    aliases: ['bal', 'creds', 'credits']
  duel:
    description: Start a duel with another player
    usage: "§c/duel help §7to begin"
    aliases: ['1v1']
  # Staff Commands
  modmode:
    description: Mod mode
    permission: SoupCore.modmode
    permission-message: Unknown command. Type "/help" for help.
    aliases: ['mod', 'admin', 'adminmode']
  tphere:
    description: Teleport to a player
    permission: SoupCore.command.tp
    permission-message: Unknown command. Type "/help" for help.
    usage: "§cUsage: /tphere <player>"
    aliases: ['tphere']
  gms:
    description: Toggle your gamemode
    permission: SoupCore.command.gamemode
    permission-message: Unknown command. Type "/help" for help.
    aliases: ['gmc', 'gmsp', 'survival', 'creative', 'spectator']
  follow:
    description: Follow a player
    permission: SoupCore.command.follow
    permission-message: Unknown command. Type "/help" for help.
    usage: "§cUsage: /follow <player>"
    aliases: ['unfollow']
  freeze:
    description: Freeze a player
    permission: SoupCore.command.freeze
    permission-message: Unknown command. Type "/help" for help.
    usage: "§cUsage: /freeze <player>"
    aliases: ['unfreeze']
  fly:
    description: Toggle flight
    permission: SoupCore.command.fly
    permission-message: Unknown command. Type "/help" for help.
  soupreload:
    description: Reload the SoupCore config
    permission: SoupCore.admin
    permission-message: Unknown command. Type "/help" for help.
  adminGiveCredits:
    description: ADMIN COMMAND
    permission: SoupCore.admin
    permission-message: Unknown command. Type "/help" for help.
permissions:
  SoupCore.admin:
    default: false
  SoupCore.kit.default:
    default: true
  SoupCore.kit.fisherman:
    default: false
  SoupCore.kit.tank:
    default: false
  SoupCore.kit.venom:
    default: false
  SoupCore.kit.stealth:
    default: false
  SoupCore.kit.mage:
    default: false
  SoupCore.kit.hulk:
    default: false
  SoupCore.kit.solider:
    default: false
  SoupCore.kit.blitz:
    default: false
  SoupCore.kit.spiderman:
    default: false
  SoupCore.kit.scientist:
    default: false
  SoupCore.kit.grappler:
    default: false
  SoupCore.kit.glider:
    default: false
  SoupCore.kit.snail:
    default: false
  SoupCore.kit.turbo:
    default: false
  SoupCore.kit.switcher:
    default: false

depend: [PlaceholderAPI, WorldGuard, LuckPerms]
