name: SoupCore
version: '${project.version}'
main: me.smeo.soupcore.SoupCore
api-version: 1.20
commands:
  ping:
    description: ping
  kits:
    description: kits
  placeholderTestCommand:
    description: Tests PlaceHolderAPI
  refill:
    description: Refill your inventory with soup for 200 credits
  repair:
    description: Repair your armour and tools for 50 credits
  adminGiveCredits:
    description: ADMIN COMMAND
  bounty:
    description: Bounty System
  giveAbilityItem:
    description: ADMIN COMMAND

depend: [PlaceholderAPI]
