name: SoupCore
version: '${project.version}'
main: me.smeo.soupcore.SoupCore
api-version: 1.20
commands:
  kits:
    description: kits
  refill:
    description: Refill your inventory with soup for 200 credits
  repair:
    description: Repair your armour and tools for 50 credits
  adminGiveCredits:
    description: ADMIN COMMAND
  bounty:
    description: Bounty System
  giveAbilityItem:
    description: ADMIN COMMAND
  stats:
    description: Stats Command
    usage: /stats [player]
  spawn:
    description: Teleport to spawn
  coinflip:
    description: Flip a coin!
    aliases: ['cf']
  pay:
    description: Pay another player credits
    usage: "&c /pay <player> <amount>"
  balance:
    description: Check your credit balance
    usage: "&c/bal [player]"
    aliases: ['bal', 'creds', 'credits']
  adminGiveCredits:
    description: ADMIN COMMAND
    permission: SoupCore.admin
    permission-message: Unknown command. Type "/help" for help.
  giveAbilityItem:
    description: ADMIN COMMAND
    permission: SoupCore.admin
    permission-message: Unknown command. Type "/help" for help.
permissions:
  SoupCore.admin:
    default: false
  SoupCore.kit.default:
    default: true
  SoupCore.kit.fisherman:
    default: false
  SoupCore.kit.tank:
    default: false
  SoupCore.kit.venom:
    default: false
  SoupCore.kit.stealth:
    default: false
  SoupCore.kit.mage:
    default: false
  SoupCore.kit.hulk:
    default: false
  SoupCore.kit.solider:
    default: false
  SoupCore.kit.blitz:
    default: false
  SoupCore.kit.spiderman:
    default: false
  SoupCore.kit.scientist:
    default: false
  SoupCore.kit.grappler:
    default: false

depend: [PlaceholderAPI, WorldGuard, LuckPerms]
